// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VereinKasseScaffolding.Data;

#nullable disable

namespace VereinKasseScaffolding.Migrations
{
    [DbContext(typeof(VereinContext))]
    [Migration("20260209084145_Eintrittsdatum")]
    partial class Eintrittsdatum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VereinKasseScaffolding.Models.Mitglied", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bild")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Eintrittsdatum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IstAktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mitglieder");
                });

            modelBuilder.Entity("VereinKasseScaffolding.Models.Zahlung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Betrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IstEinzahung")
                        .HasColumnType("bit");

                    b.Property<int>("MitgliedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MitgliedId");

                    b.ToTable("Zahlungen");
                });

            modelBuilder.Entity("VereinKasseScaffolding.Models.Zahlung", b =>
                {
                    b.HasOne("VereinKasseScaffolding.Models.Mitglied", "Mitglied")
                        .WithMany()
                        .HasForeignKey("MitgliedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mitglied");
                });
#pragma warning restore 612, 618
        }
    }
}
